package com.example.hbv601G.entities;

public class User {
    private long ID; // generated by database?
    private String username;
    private String password;
    private String email;

    // meira seinna, tengar og sfr.

    public User(){}

    public User(String username, String password){
        this.username=username;
        this.password=password;
    }
    public User(String username, String password, String email){
        this.username=username;
        this.password=password;
        this.email=email;
    }

    public long getID(){
        return ID;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}
